title: Dejan Seretinek # your name (or website title) here
logo: "/images/Profile ImageTransparent.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Date of birth: 14.8. 1988
  Age: 32
  Location: Zadar / Novska, Croatia
  <br>
  dejanseretinek@gmail.com 
  <br>Phone: +38591 941 1145
  
  <br>
  <b>Programming skills</b>
  <br>
  - C#
  <br>

  <b>Digital Art</b>
  <br>
  - Adobe Photoshop
  <br>
  - Adobe Illustrator
  <br>
  - Adobe Premiere
  <br>
  - Adobe After Effects
  <br>
  <b>Game Engines</b>
  <br>
  - Unity
  <br>
  <b>3D Modelling and Animations</b>
  <br>
  - Autodesk 3d's Max
  <br>
  - Blender
  <br>
  - Substance Painter
  <br>
  <b>Other</b>
  <br>
   - HTML
  <br>
  - CSS
  <br>
  - Wordpress
  <br>
  
  <a href="https://www.linkedin.com/in/dejan-seretinek-144b2656/">View My LinkedIn Profile</a> 
  <br>
  <a href="https://www.artstation.com/dejanseretinek/">View My ArtStation Page</a> 
  <br>
  <a href="https://www.freelancer.com/u/dejanseretinek/">View My Freelancer.com Page</a> 
  
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
