title: Dejan Seretinek # your name (or website title) here
logo: "/images/Profile Image.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Date of birth: 14.8. 1988
  Age: 32
  Location: Zadar / Novska, Croatia
  
  
  <br><br>
  Programming skills
  -Unity C#
  - Adobe Photoshop
  - HTML
  - CSS
  - Fuse
  - Adobe Illustrator
  - Adobe After Effects
  - Adobe Premiere
  - Autodesk 3d's Max
  - Adobe Dreamweaver
  
  <br><br>
  <a href="https://www.linkedin.com/in/dejan-seretinek-144b2656/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
